spring.application.name=demo

# ==========================================
# Configuração de Conexão com o PostgreSQL
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/t_pds_agromanagement
spring.datasource.username=postgres
spring.datasource.password=SUA_SENHA
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# Configuração do Hibernate/JPA
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Como você já tem as tabelas criadas no banco, o 'update' apenas garante que
# o código Java e o banco estão sincronizados, sem apagar seus dados.
spring.jpa.hibernate.ddl-auto=update

# Exibe os comandos SQL no terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# Configuração de Segurança (JWT)
# ==========================================
api.security.token.secret=agro-management-system-secret-key-2026

logging.level.org.springframework.security=TRACE